export const revenueSeries = [
  { day: "Jul 1", revenue: 42, pinterest: 22, youtube: 14, products: 6 },
  { day: "Jul 3", revenue: 58, pinterest: 30, youtube: 18, products: 10 },
  { day: "Jul 5", revenue: 71, pinterest: 34, youtube: 22, products: 15 },
  { day: "Jul 7", revenue: 65, pinterest: 32, youtube: 20, products: 13 },
  { day: "Jul 9", revenue: 88, pinterest: 40, youtube: 28, products: 20 },
  { day: "Jul 11", revenue: 96, pinterest: 44, youtube: 32, products: 20 },
  { day: "Jul 13", revenue: 112, pinterest: 52, youtube: 36, products: 24 },
  { day: "Jul 15", revenue: 128, pinterest: 58, youtube: 42, products: 28 },
  { day: "Jul 17", revenue: 141, pinterest: 62, youtube: 46, products: 33 },
  { day: "Jul 19", revenue: 156, pinterest: 68, youtube: 52, products: 36 },
  { day: "Jul 21", revenue: 174, pinterest: 76, youtube: 58, products: 40 },
  { day: "Jul 23", revenue: 168, pinterest: 74, youtube: 54, products: 40 },
  { day: "Jul 25", revenue: 192, pinterest: 84, youtube: 62, products: 46 },
  { day: "Jul 27", revenue: 214, pinterest: 92, youtube: 70, products: 52 },
  { day: "Jul 29", revenue: 236, pinterest: 102, youtube: 78, products: 56 },
  { day: "Jul 31", revenue: 258, pinterest: 112, youtube: 86, products: 60 },
];

export const niches = [
  {
    id: "health",
    name: "Health & Fitness",
    revenue: 1284.4,
    growth: 12.4,
    color: "#10b981",
    soft: "#ecfdf5",
    spark: [12, 18, 16, 24, 22, 30, 34, 38, 42, 46, 52, 58],
  },
  {
    id: "luxury",
    name: "Luxury & Tech",
    revenue: 946.2,
    growth: 8.7,
    color: "#f59e0b",
    soft: "#fef7e6",
    spark: [8, 12, 14, 18, 16, 22, 24, 28, 26, 32, 34, 40],
  },
  {
    id: "ai",
    name: "AI & Making Money",
    revenue: 620.15,
    growth: 22.1,
    color: "#2c5aa0",
    soft: "#e8f0f9",
    spark: [4, 6, 10, 12, 16, 20, 22, 28, 34, 40, 48, 56],
  },
];

export const topPerformers = {
  pins: [
    { title: "10 Home Workouts That Actually Work", niche: "Health", clicks: 3240, revenue: 128.4 },
    { title: "Minimalist Desk Setup 2026", niche: "Luxury", clicks: 2180, revenue: 94.2 },
    { title: "5 AI Tools I Use Daily", niche: "AI", clicks: 1840, revenue: 76.5 },
  ],
  videos: [
    { title: "The 20-Minute Morning Routine", niche: "Health", views: 18400, revenue: 214.8 },
    { title: "iPhone 17 vs Pixel 11", niche: "Luxury", views: 12200, revenue: 148.3 },
    { title: "Claude vs ChatGPT for Writers", niche: "AI", views: 9600, revenue: 112.4 },
  ],
  products: [
    { title: "Notion Fitness Tracker Template", type: "Template", sales: 42, revenue: 588 },
    { title: "AI Prompt Vault (200+ prompts)", type: "Guide", sales: 68, revenue: 812 },
    { title: "Passive Income Blueprint", type: "Course", sales: 14, revenue: 966 },
  ],
};

export const recentActivity = [
  { type: "sale", label: "Product sale — AI Prompt Vault", meta: "$12 · 3 min ago", color: "#10b981" },
  { type: "click", label: "48 new clicks on Pinterest pin", meta: "Health & Fitness · 18 min ago", color: "#2c5aa0" },
  { type: "conversion", label: "Affiliate conversion — Amazon", meta: "$8.40 commission · 1h ago", color: "#f59e0b" },
  { type: "publish", label: "YouTube video published", meta: "iPhone 17 review · 2h ago", color: "#4a7bc4" },
  { type: "sale", label: "Product sale — Notion Template", meta: "$14 · 4h ago", color: "#10b981" },
];

export const affiliateLinks = [
  {
    id: "1",
    product: "Bowflex SelectTech Dumbbells",
    slug: "auto/dumbbells",
    niche: "Health",
    network: "Amazon Associates",
    commission: "4%",
    clicks: 1284,
    conversions: 42,
    revenue: 486.4,
    active: true,
  },
  {
    id: "2",
    product: "Sony WH-1000XM6 Headphones",
    slug: "auto/xm6",
    niche: "Luxury",
    network: "Amazon Associates",
    commission: "3%",
    clicks: 962,
    conversions: 28,
    revenue: 384.2,
    active: true,
  },
  {
    id: "3",
    product: "Notion for Teams",
    slug: "auto/notion",
    niche: "AI",
    network: "Notion Partners",
    commission: "50%",
    clicks: 540,
    conversions: 18,
    revenue: 216.0,
    active: true,
  },
  {
    id: "4",
    product: "MasterClass Annual",
    slug: "auto/masterclass",
    niche: "AI",
    network: "Impact",
    commission: "$25 CPA",
    clicks: 312,
    conversions: 6,
    revenue: 150.0,
    active: false,
  },
];

export const products = [
  {
    id: "1",
    name: "Notion Fitness Tracker Template",
    type: "Template",
    description: "A complete Notion workspace for tracking workouts, meals and progress photos.",
    price: 14,
    sales: 42,
    revenue: 588,
    margin: 96,
    accent: "#2c5aa0",
    soft: "#e8f0f9",
  },
  {
    id: "2",
    name: "AI Prompt Vault",
    type: "Guide",
    description: "200+ tested prompts for writing, coding, marketing and research. PDF + Notion.",
    price: 19,
    sales: 68,
    revenue: 1292,
    margin: 94,
    accent: "#f59e0b",
    soft: "#fef7e6",
  },
  {
    id: "3",
    name: "Passive Income Blueprint",
    type: "Course",
    description: "6-module course on building automated income streams from your phone.",
    price: 69,
    sales: 14,
    revenue: 966,
    margin: 88,
    accent: "#10b981",
    soft: "#ecfdf5",
  },
  {
    id: "4",
    name: "Content Calendar Checklist",
    type: "Template",
    description: "Weekly Pinterest + YouTube schedule template. Import into any calendar app.",
    price: 9,
    sales: 96,
    revenue: 864,
    margin: 98,
    accent: "#2c5aa0",
    soft: "#e8f0f9",
  },
];

export const contentLibrary = Array.from({ length: 8 }, (_, i) => ({
  id: `${i}`,
  title: [
    "10 Home Workouts That Actually Work",
    "Minimalist Desk Setup 2026",
    "5 AI Tools I Use Daily",
    "The 20-Minute Morning Routine",
    "iPhone 17 vs Pixel 11",
    "Claude vs ChatGPT for Writers",
    "Best Standing Desk Under $400",
    "Passive Income From Pinterest",
  ][i],
  niche: ["Health", "Luxury", "AI", "Health", "Luxury", "AI", "Luxury", "AI"][i],
  platform: ["Pinterest", "Pinterest", "YouTube", "YouTube", "YouTube", "Pinterest", "Pinterest", "YouTube"][i],
  status: ["Published", "Published", "Scheduled", "Published", "Published", "Draft", "Published", "Scheduled"][i],
  date: ["Jul 24", "Jul 22", "Jul 21", "Jul 19", "Jul 17", "Jul 15", "Jul 14", "Jul 12"][i],
  views: [12400, 8200, 9600, 18400, 12200, 0, 6400, 0][i],
  clicks: [3240, 2180, 1840, 4200, 3100, 0, 1820, 0][i],
  conversions: [42, 28, 18, 62, 44, 0, 22, 0][i],
  hue: [200, 30, 220, 160, 20, 240, 40, 210][i],
}));
